"""Generate a reading note for every study read into the reporting matrix.

WHY THIS IS GENERATED AND NOT HAND-WRITTEN. The project rule is that no
citation appears in either paper without a PDF in `lit/`, a VERIFIED or PARTIAL
row in `VERIFICATION.md`, and a note in `lit/notes/`. The second literature
sweep added seven studies to the reference list and produced a full, evidence-
quoted reading of each -- but the readings live in
`paper-a/data/reference/raw/`, not in `lit/notes/`, so the third leg of the gate
was missing for all seven. An audit found it.

Hand-writing seven notes from the same readings would introduce transcription
where none is needed. This renders them, so a note cannot drift from the
evidence it was built on: re-running it after a re-reading regenerates the note.

Notes for works that were read directly rather than through the matrix --
Benjamini & Hochberg, Bertrand & Mullainathan, Simonsohn et al., Steegen et al.,
An & Rudinger, Seshadri et al., He et al. -- are written by hand and are NOT
touched by this script. It only writes files whose header marks them generated.

    C:/research-toolchain/venv/Scripts/python.exe paper-a/src/build_lit_notes.py
"""
from __future__ import annotations

import json
import pathlib
import re
import sys

try:
    sys.stdout.reconfigure(encoding="utf-8")
except Exception:  # noqa: BLE001
    pass

ROOT = pathlib.Path(__file__).resolve().parents[2]
MATRIX = ROOT / "paper-a" / "data" / "reference" / "reporting_practice_matrix.json"
NOTES = ROOT / "lit" / "notes"

MARK = "<!-- generated by paper-a/src/build_lit_notes.py -->"

# Studies whose notes are hand-written from a direct full-text read. Never
# overwrite these.
HAND_WRITTEN = {
    "An et al. 2024", "Fu & Shi 2025", "Gao et al. 2026", "Iso et al. 2025",
    "Tan et al. 2026", "Wilson & Caliskan 2024", "Sclar et al. 2024",
    "Seshadri et al. 2025",
    "Bertrand & Mullainathan 2004",
}

# The fields worth surfacing in a note, in the order a reader wants them.
ORDER = [
    ("headline_effect", "Headline effect"),
    ("name_list_source", "Name list"),
    ("names_per_race", "Names per race"),
    ("n_occupations", "Occupations"),
    ("n_wordings_used", "Wordings used"),
    ("n_wordings_separately_estimated", "Wordings separately estimated"),
    ("dispersion_across_wordings", "Dispersion across wordings"),
    ("null_edit_control", "Null-edit control"),
    ("name_sensitivity_reported", "Name-draw sensitivity"),
    ("token_matching", "Token matching"),
    ("checkpoint_pinned", "Checkpoint pinned"),
    ("quantization_reported", "Quantization"),
    ("serving_stack", "Serving stack"),
    ("concurrency_or_batching", "Batching"),
    ("cache_policy", "Cache policy"),
    ("decoding_params", "Decoding parameters"),
    ("n_repeats", "Repeats"),
    ("resampling_unit", "Resampling unit"),
    ("multiplicity_correction", "Multiplicity correction"),
    ("reporting_scale", "Reporting scale"),
    ("code_or_data_released", "Code / data released"),
]

SYM = {"reported": "**reported**", "partial": "*partial*",
       "not-reported": "**NOT REPORTED**", "not-applicable": "n/a"}


def slug(label: str) -> str:
    s = label.lower().replace("&", "and")
    s = re.sub(r"[^a-z0-9]+", "_", s).strip("_")
    return s


def main() -> int:
    if not MATRIX.exists():
        print("no reporting matrix; run build_reporting_matrix.py first",
              file=sys.stderr)
        return 1
    m = json.loads(MATRIX.read_text(encoding="utf-8"))
    NOTES.mkdir(parents=True, exist_ok=True)
    written = skipped = 0

    for s in m["studies"]:
        label = s["label"]
        if label in HAND_WRITTEN:
            skipped += 1
            continue
        path = NOTES / f"{slug(label)}.md"
        if path.exists() and MARK not in path.read_text(encoding="utf-8"):
            print(f"  refusing to overwrite hand-written {path.name}")
            skipped += 1
            continue

        cells = s["cells"]
        lines = [MARK, "",
                 f"# {label}", "",
                 "**Generated from the full-text reading behind the "
                 "reporting-practice matrix.** Every verdict below was produced "
                 "by reading the paper end to end; every negative was "
                 "re-checked independently against a fresh extraction of the "
                 "PDF. Raw readings, including the evidence quotes in full, are "
                 "under `paper-a/data/reference/raw/`. Edit "
                 "`build_lit_notes.py` or the raw readings, not this file.",
                 ""]
        if s.get("reference"):
            lines += ["**Reference as used in the paper.** " + s["reference"], ""]
        if s.get("citation_check"):
            cc = " ".join(s["citation_check"].split())
            lines += ["**Title page, as printed.** " + cc[:1200], ""]
        lines += ["## Reporting practice", ""]
        for key, pretty in ORDER:
            c = cells.get(key)
            if not c:
                continue
            v = SYM.get(c["verdict"], c["verdict"])
            val = " ".join((c.get("value") or "").split())
            ev = " ".join((c.get("evidence") or "").split())
            lines.append(f"- **{pretty}** — {v}. {val[:400]}")
            if ev:
                lines.append(f"  - *evidence:* {ev[:400]}")
        if s.get("negative_check"):
            nc = " ".join(s["negative_check"].split())
            lines += ["", "## Independent re-check of every negative", "",
                      nc[:1800]]
        lines.append("")
        path.write_text("\n".join(lines), encoding="utf-8")
        written += 1
        print(f"  wrote {path.relative_to(ROOT)}")

    print(f"\n{written} generated, {skipped} hand-written or protected")
    return 0


if __name__ == "__main__":
    sys.exit(main())
