"""The correction must be applied to both panels, or to neither.

THE DEFECT THIS PINS. §4.7.1 computed a replicate noise floor for the frontier
API models, subtracted it from their between-wording SD, quoted the corrected
dispersion-to-effect ratio in the abstract -- and left the open-weight ratios
uncorrected, stating that "the local floor is zero". It is not. Study 2's own
S1/N1 replicate agrees bitwise on 13.9 % to 66.7 % of cells, and the same
estimator gives local floors of 0.029 and 0.035 on the two identified
checkpoints -- the latter numerically equal to gpt-4o's.

The evidence was already in the repository twice over: noise_floor.json records
the bitwise fractions, and §5.2 states them in prose. The "284 of 284 identical"
result cited for the zero belongs to the SECOND-TASK study on housing and
moderation, run under a serving configuration Study 2 predates.

Nothing numeric could have caught this. Every published figure was correctly
computed; what was wrong was that one panel went through the estimator and the
other did not, while the paper compared their outputs. So these tests assert
SYMMETRY rather than values.
"""
from __future__ import annotations

import collections
import json
import pathlib
import sys

import numpy as np
import pytest

ROOT = pathlib.Path(__file__).resolve().parents[1]
SRC = ROOT / "paper-a" / "src"
DATA = ROOT / "paper-a" / "data"
sys.path.insert(0, str(SRC))


def _load(p):
    if not p.exists():
        pytest.skip(f"{p.name} not built")
    return json.loads(p.read_text(encoding="utf-8"))


def _floor():
    return _load(DATA / "frontier" / "frontier_noise_floor.json")


def test_both_panels_are_present_in_the_artifact():
    f = _floor()
    panels = collections.Counter(v.get("panel") for v in f["models"].values())
    assert panels["frontier"] >= 1
    assert panels["local"] >= 1, (
        "the open-weight panel is missing; the correction is asymmetric again")


def test_both_panels_have_a_summary():
    f = _floor()
    assert "summary_frontier" in f
    assert "summary_local" in f


def test_the_local_floor_is_not_zero():
    """The claim that started this. If a re-run makes it zero, say so knowingly."""
    f = _floor()
    s = f["summary_local"]
    assert not s["floor_is_zero_on_every_model"], (
        "the local floor is now zero on every model; §4.7.1's text must be "
        "revisited rather than left describing a non-zero floor")
    assert s["max_noise_sd_of_a_wording_mean"] > 0


def test_the_local_panel_is_not_bitwise_deterministic_on_study_2():
    f = _floor()
    s = f["summary_local"]
    assert s["min_frac_bitwise_identical"] < 1.0
    assert s["max_frac_bitwise_identical"] < 1.0, (
        "Study 2 now reproduces bitwise everywhere; the 284/284 comparison "
        "would become apt and the prose should change")


def test_every_corrected_model_carries_both_the_published_and_corrected_ratio():
    f = _floor()
    for m, v in f["models"].items():
        if not v.get("usable") or v.get("ratio_sd_to_effect_corrected") is None:
            continue
        assert v.get("published_ratio_sd_to_effect") is not None, m
        assert v["ratio_sd_to_effect_corrected"] <= \
            v["published_ratio_sd_to_effect"] + 1e-12, m


def test_both_panels_go_through_one_function():
    """Structural: two code paths are how the asymmetry happened."""
    src = (SRC / "analyze_frontier_noise.py").read_text(encoding="utf-8")
    assert src.count("def floor_for(") == 1
    assert src.count("floor_for(") >= 3, (
        "floor_for is not called for both panels")


def test_the_paper_no_longer_claims_the_local_floor_is_zero():
    pdf = ROOT / "paper-a" / "figures" / "paper_instrument_validity_v3.pdf"
    if not pdf.exists():
        pytest.skip("paper not built")
    fitz = pytest.importorskip("fitz")
    with fitz.open(pdf) as doc:
        t = " ".join(" ".join(p.get_text().split()) for p in doc)
    for banned in ("because the local floor is zero",
                   "which the local panel does not need because its floor is "
                   "zero",
                   "Only the frontier side needs correcting"):
        assert banned not in t, f"the withdrawn claim is back: {banned}"


def test_the_estimator_reproduces_independently_on_the_local_panel():
    """Recompute one local floor from raw rows, without the module.

    Guards against the artifact being regenerated by something that quietly
    drops the local panel again: if this value stops matching, the artifact and
    the data have parted company.
    """
    f = _floor()
    m = "llama-3.1-8b-instruct"
    rec = f["models"].get(m)
    if not rec or not rec.get("usable"):
        pytest.skip("local panel not built")

    def sup(w, b):
        return 1.0 if w > b else (0.0 if w < b else 0.5)

    by = collections.defaultdict(dict)
    for p in sorted((DATA / "delta_stability").glob("*.jsonl")):
        for ln in p.read_text(encoding="utf-8").splitlines():
            if not ln.strip():
                continue
            r = json.loads(ln)
            if r.get("model") != m or r.get("variant") not in ("S1", "N1"):
                continue
            by[(r.get("template"), r.get("pair"))][r["variant"]] = r
    a_by, b_by = collections.defaultdict(list), collections.defaultdict(list)
    for (_t, pair), v in by.items():
        a, b = v.get("S1"), v.get("N1")
        if not a or not b:
            continue
        if any(x.get(f"{arm}_margin") is None
               for x in (a, b) for arm in ("white", "black")):
            continue
        a_by[pair].append(sup(a["white_margin"], a["black_margin"]))
        b_by[pair].append(sup(b["white_margin"], b["black_margin"]))
    pairs = sorted(set(a_by) & set(b_by))
    # SKIPS IN THE PUBLIC RELEASE. This re-derives the noise floor from the raw
    # per-call records rather than trusting the artifact, which is the whole
    # point of it -- and those records are gigabytes and are not shipped. With
    # no pairs the standard deviation is nan, and `nan < 1e-12` fails in a way
    # that looks like a broken estimator rather than a missing input.
    if len(pairs) < 2:
        pytest.skip("raw per-call records not present; expected in the public "
                    "release, which ships the derived artifacts only")
    dp = np.array([np.mean(a_by[p]) - np.mean(b_by[p]) for p in pairs])
    mine = float(dp.std(ddof=1) / np.sqrt(2 * len(pairs)))
    assert abs(mine - rec["noise_sd_of_a_wording_mean"]) < 1e-12
    assert mine > 0
